version: '3.8'

services:
  auth-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: auth-server
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - ../logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s