version: '3.8'

services:
  flask-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flask-server
    ports:
      - "5000:5000"
    env_file:
      - ../.env    # This is enough to load all environment variables
    volumes:
      - ..:/app    # Use relative path to mount the app directory
      - ../logs:/app/logs    # Use relative path for logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s